### ISSUE TITLE
Kicking out after can't encode character error

### ISSUE THREAD

**Issue by snewt-uga** [djtech42/YikYakTerminal#14]
Title says it all. I think it could be emojis kicking it out again? Can I filter that out before I read, somehow? 
![image](https://cloud.githubusercontent.com/assets/8352627/5742797/ce6f4c7a-9be2-11e4-8e2b-29c57f8a38d6.png)

**Comment by ankerMan** [comment]
Yup its emojis, just get the exempting function that kills them. I dont
know where it is, might still be the beta if it hasn't been updated recently

On Wed, Jan 14, 2015 at 11:46 AM, snewt-uga <notifications@github.com>
wrote:

> Title says it all. I think it could be emojis kicking it out again? Can I
> filter that out before I read, somehow?
> [image: image]
> <https://cloud.githubusercontent.com/assets/8352627/5742797/ce6f4c7a-9be2-11e4-8e2b-29c57f8a38d6.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/djtech42/YikYakTerminal/issues/14>.
>



-- 
Very Respectfully,
Dennis M. Devey
MIDN          USN

**Comment by snewt-uga** [comment]
Alrighty, thank you.

**Comment by djtech42** [comment]
Are you using the latest version?

**Comment by NsValleyMan** [comment]
I had this issue as well.... I fixed it by explicitly encoding the string. 
Line 177: API.py
replace current line with....
				print ("### %s ###" % self.handle.encode('utf-8').strip())
